## 测试环境238
#
#
#
# server config
DebugMode = 1
ServerID = "120.78.95.238_22000" # websocket服务ID 格式 ip_port

# websocket server config
WebsocketPort = 22000
Des3Key4WsMsg = "c21d31be-4300-4881-a553-156ebb5df087" # Websocket消息加解密Key
EntryTimeInterval = 5 # 入场时间间隔
PingTimeInterval = 100 # 心跳时间间隔
OnlineInfoStatisticInterval = 8 # 在线信息统计时间间隔

# consul
ConsulAddr = "172.18.146.113:8500"

# api server config
[ApiServerConf]
    ServerAddr = "172.18.146.113"
    ServerName = "tl-ws-server"
    ServerID   = "tl-ws-server-dev-33000"
    ApiPort = 33000

# pprof config
[PprofConf]
    PprofPort = 23000
    Disabled = 1

# redis
[[RedisConf]]
    Name= "db1"
    Addr= "172.18.146.113:6379"
    Active= 100
    Idle= 30
    DialTimeout= 5
    ReadTimeout= 2
    WriteTimeout= 2
    IdleTimeout= 60
    DBNum= "5"
    Password= "41IuR5Oj8Yo9"

# mongo
[[MongoConf]]
    Name= "db1"
    URL = "mongodb://tl:ayq1w8FTF7Ng@120.78.88.150:27017,172.18.146.114:27017/tl_pre?readPreference=primary"
    Database= "tl_pre"

# mysql
[[MysqlConf]]
      URL = "root:ayq1w8FTF7Ng@tcp(172.18.146.111:3306)/tl_live?charset=utf8&loc=Local&parseTime=true"
      Driver = "mysql"
      IdleSize = 4
      MaxSize = 20
      MaxLifeTime = 60
      SqlDebug = 1
      Memory = false


# kafka producer config
[ProducerConf]
    BrokerList = ["120.78.186.114:9092"]
    BatchNum = 3

#kafka consumer config
[ConsumerConf]
    [ConsumerConf.Biz]                                  # 业务处理
        version                 = "2.2.0"               # kafka版本
        topics                  = [
            "ws_biz"                                    # 订阅的topic
        ]
        group_id                = 'ws_biz'        # 消费者组ID
        broker_addresses        = [                     # broker地址组
            "120.78.186.114:9092"
        ]                    

    [ConsumerConf.ExternalFoo]                          # 三方消息处理
        version                 = "2.2.0"               # kafka版本
        topics                  = [                     
            "entry"                                     # 用户入场 
        ]                                               # 订阅的topic
        group_id                = 'ws_foo'        # 消费者组ID
        broker_addresses        = [                     # broker地址组
            "120.78.186.114:9092"
        ]

    [ConsumerConf.ExternalBar]                          # 三方消息处理
        version                 = "2.2.0"               # kafka版本
        topics                  = [
            "notifyOnlineUser"
        ]                                               # 订阅的topic                    
        group_id                = 'ws_bar'        # 消费者组ID
        broker_addresses        = [                     # broker地址组
            "172.18.146.113:9092"
        ]
