## 开发环境
#
#
#
# server config
DebugMode = 1
ServerID = "192.168.88.202_22000" # websocket服务ID 格式 ip_port

# websocket server config
WebsocketPort = 22000
Des3Key4WsMsg = "c21d31be-4300-4881-a553-156ebb5df087" # Websocket消息加解密Key
EntryTimeInterval = 5 # 入场时间间隔
PingTimeInterval = 100 # 心跳时间间隔
OnlineInfoStatisticInterval = 8 # 在线信息统计时间间隔

# consul
ConsulAddr = "192.168.88.202:8500"

# api server config
[ApiServerConf]
    ServerAddr = "192.168.88.202"
    ServerName = "tl-ws-server"
    ServerID   = "tl-ws-server-dev-33000"
    ApiPort = 33000

# pprof config
[PprofConf]
    PprofPort = 23000
    Disabled = 1

# redis
[[RedisConf]]
    Name= "db1"
    Addr= "192.168.88.207:6379"
    Active= 100
    Idle= 30
    DialTimeout= 5
    ReadTimeout= 2
    WriteTimeout= 2
    IdleTimeout= 60
    DBNum= "1"
    Password= "eJPSh5mw"

# mongo
[[MongoConf]]
    Name= "db1"
    URL = "mongodb://tl:eJPSh5mw@192.168.88.207:27017,192.168.88.207:27018/tl?readPreference=primary"
    Database= "tl"

# mysql
[[MysqlConf]]
      URL = "root:zc8BSr9w@tcp(192.168.88.207:3306)/tl_live?charset=utf8&loc=Local&parseTime=true"
      Driver = "mysql"
      IdleSize = 4
      MaxSize = 20
      MaxLifeTime = 60
      SqlDebug = 1
      Memory = false


# kafka producer config
[ProducerConf]
    BrokerList = ["192.168.88.202:9092"]
    BatchNum = 3

#kafka consumer config
[ConsumerConf]
    [ConsumerConf.Biz]                                  # 业务处理
        version                 = "2.2.0"               # kafka版本
        topics                  = [
            "ws_biz"                                    # 订阅的topic
        ]
        group_id                = 'ws_biz'        # 消费者组ID
        broker_addresses        = [                     # broker地址组
            "192.168.88.202:9092"
        ]                    

    [ConsumerConf.ExternalFoo]                          # 三方消息处理
        version                 = "2.2.0"               # kafka版本
        topics                  = [                     
            "entry"                                     # 用户入场 
        ]                                               # 订阅的topic
        group_id                = 'ws_foo'        # 消费者组ID
        broker_addresses        = [                     # broker地址组
            "192.168.88.202:9092"
        ]

    [ConsumerConf.ExternalBar]                          # 三方消息处理
        version                 = "2.2.0"               # kafka版本
        topics                  = [
            "notifyOnlineUser"
        ]                                               # 订阅的topic                    
        group_id                = 'ws_bar'        # 消费者组ID
        broker_addresses        = [                     # broker地址组
            "192.168.88.207:9092"
        ]                      
